baseURL = "/"
title = "feministclickback"

[params]
logo = "images/logo.png"
languageCode = "de"
subtitle = "Suchmaschinenoptimierung für feministische Webseiten"

[permalinks]
  categories = "/kategorie/:title/"
